### ISSUE TITLE
Upgradeability

### ISSUE THREAD

**Issue by jfschwarz** [gnosis/wand-nft#24]
@samepant mentioned it would be nice if we'd be able to update the way wands are rendered in the future. I see two ways for implementing this:

### 1) Make Wand.sol `OwnableUpgradeable`

Allows us to update all aspects of wands, including the XP system etc. 

### 2) Allow `owner` to update the `wandConjuror`

This allows us to only update the rendering part, so we wouldn't be able to mess with wand ownership, etc.

**Comment by samepant** [comment]
I'm in favor of `2`, since we could make the owner of the contract the eventual DAO of nft holders, and allow governance to decide upgrading of the conjuror. This is similar to how the [Nouns DAO contracts](https://etherscan.io/address/0x9C8fF314C9Bc7F6e59A9d9225Fb22946427eDC03#code) works, they built in the ability to change the `NounsDescriptor`, which is the [contract which handles the visual components](https://etherscan.io/address/0x0cfdb3ba1694c2bb2cfacb0339ad7b1ae5932b63#code).

In a more mainstream NFT project, I see how this could be an issue, as the artwork is generally the core focus of a token. Since our token is more about community and governance in the long term than the actual artwork itself, I think building in a way for the community of token holders to change the way they visually represent themselves is pretty crucial.

**Comment by samepant** [comment]
We've decided to go with option 2, ZodiacWands will be able to swap out the Conjuror contract (which handles svg representation) and the Forge contract (which handles xp and item level)
