### ISSUE TITLE
Sparkles not randomly placed

### ISSUE THREAD

**Issue by samepant** [gnosis/wand-nft#35]
On reload all the sparkles stay in the same place, these should be randomly placed roughly within the diameter of the halo.

<img src="https://user-images.githubusercontent.com/6718506/179651778-4e4a2fdb-a6a9-401d-a71f-70928ed34358.png" width="300px" />

**Comment by jfschwarz** [comment]
This issue touches on the question on how we bring randomness into the SVG rendering.

So far we're using the token ID as the seed for randomness used for placing the sparkles, deriving the wand name, as well as for generating the stone textures. Using the token ID is convenient for the following reasons:

- It is unique, meaning no two wands will have the same sparkles patterns. Also every wand will have a unique stone texture.
- It is continuous, meaning that we cycle through the words making up wand names in an optimal fashion (no duplicate names before wand #599675)

However, now that we've folded minting and building into a single call, the tokenID is not predictable anymore, since there's a potential race condition with other users. So if you spend too much time in the minting app for fine-tuning the wand visuals someone else might mint that token ID in the meanwhile and you'd end up getting a wand with different name, sparkles and slightly different stone texture than in the preview.

**Comment by jfschwarz** [comment]
We could maybe create the randomness seed as a combination of the address of the user and the minting block number. The app could then poll the latest block number and keep the preview updated.

**Comment by samepant** [comment]
> However, now that we've folded minting and building into a single call, the tokenID is not predictable anymore, since you're in a race with other users. So if you spend too much time in the minting app for fine-tuning the wand visuals someone else might mint that token ID in the meanwhile and you'd end up getting a wand with different name, sparkles and slightly different stone texture than in the preview.

Right, and I think this is unpredictable enough that we should wait and only show the name and the sparkles on minted wands, and let them be blank in the UI. That way there are no surprises and the name and sparkles are signifiers that a wand image has been fully minted.
