### ISSUE TITLE
UX Intro to Minting Process

### ISSUE THREAD

**Issue by samepant** [gnosis/wand-nft#45]
Currently, a potential minter (and therefore potential new member of the community) lands on the minting app and is immediately in the interface for generating their NFT. 

We could precede this with an "Intro State", where we offer a little onboarding into what this project is all about. This is an opportunity to talk about some of the mechanics of the NFT as well as what our team values, and why we built this system the way we did. The "Intro" could be as simple as a brief text and some images, or even more expansive if we've got time :)

**Comment by eccogrinder** [comment]
Yeah, having an "Intro State" would be nice. Maybe it could be a modal (scroll) that has a stripped-down summary of the key points from Kei's blog post + a field (keyhole/cavern/tinder) for people to verify (check/cast/ignite) their address (key/spell/fuel) for entry (⍝).

Hosting a longer piece would be nice too, though, because it could keep the experience self-contained.
